on: 
  pull_request:
    branches:
      - development

name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install Dependency
      uses: php-actions/composer@v6
      with:
        php_version: '8.2'
        php_extensions: gd zip curl
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Check Standard
      run: ./vendor/bin/phpcbf  --standard=PSR12 app
